artifact_uri: file:///home/schurgerfoy%40chapman.edu/MRI-classifier/mlruns/1/a4f7a2a939734906901b9cd06c980329/artifacts
end_time: 1616002694030
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a4f7a2a939734906901b9cd06c980329
run_uuid: a4f7a2a939734906901b9cd06c980329
source_name: ''
source_type: 4
source_version: ''
start_time: 1616002687126
status: 3
tags: []
user_id: schurgerfoy@chapman.edu
