artifact_uri: file:///home/schurgerfoy%40chapman.edu/MRI-classifier/mlruns/1/e3a8e4d62d0142999db9d5b141352eb0/artifacts
end_time: 1616450387063
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: e3a8e4d62d0142999db9d5b141352eb0
run_uuid: e3a8e4d62d0142999db9d5b141352eb0
source_name: ''
source_type: 4
source_version: ''
start_time: 1616450379532
status: 3
tags: []
user_id: schurgerfoy@chapman.edu
